name: Build Resume and Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Resume
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            resume.typ
            template.typ

      - name: Set file name
        id: filename
        run: echo "FILENAME=${FIRST_NAME}_${SUR_NAME}_Resume.pdf" >> $GITHUB_ENV
        env:
          FIRST_NAME: ${{ vars.FIRST_NAME }}
          SUR_NAME: ${{ vars.SUR_NAME }}

      - name: Rename PDF file
        run: mv resume.pdf ${{ env.FILENAME }}

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path: ${{ env.FILENAME }}

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: ${{ env.FILENAME }}
