name: Build Resume and Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Resume
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            resume.typ
            template.typ

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDFs
          path: resume.pdf

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: resume.pdf
